### ISSUE TITLE
How to run NaiveSharp

### ISSUE THREAD

**Issue by wyw1018** [KevinZonda/NaiveSharp#2]
All after I downloaded the zip file and unzipped it are the fowllowing directories:
.idea
NaiveSharp
NaiveSharp.Test
Screenshots and files:
.editorconfig
.gitignore
LICENSE
NaiveSharp.sln
README.md
How do I run NaiveSharp?

**Comment by ghost** [comment]
https://github.com/KevinZonda/NaiveSharp/releases
You just download source code instead of binary file

**Comment by KevinZonda** [comment]
@wyw1018 download release, run NaiveSharp.exe, lol

**Comment by KevinZonda** [comment]
@wyw1018 if you have vs (2017+) or rider, you can compile it by yourself. But do not forget to copy 3rd folder to NaiveSharp.exe path, :)
