### ISSUE TITLE
NaiveProxy似乎已经把 padding 这个字段去掉了。

### ISSUE THREAD

**Issue by proxysu** [KevinZonda/NaiveSharp#5]
https://github.com/klzgrad/naiveproxy/blob/master/USAGE.txt
这是其官方的使用说明，没有找到padding这个字段。

**Comment by KevinZonda** [comment]
是的，上游已经移除了padding，但是 USAGE.TXT 似乎并没有更新，可以参阅以下内容。

https://github.com/klzgrad/naiveproxy/blob/1d0682ee5bae6e648cd43c65f49b4eefd224f206/src/net/tools/naive/naive_proxy_bin.cc#L129-L148

https://github.com/KevinZonda/NaiveSharp/issues/1

https://github.com/klzgrad/naiveproxy/commit/e8e4f772a348b4a28dc21c617a1a90bf5a765daa

**Comment by KevinZonda** [comment]
@proxysu Wait, USAGE.TXT 也移除了 padding 内容了
